#!/usr/bin/env python3
"""Build airports.js — official per-airport drone-prohibition polygons.

Source: the CAA drone-map ArcGIS feature service (the same data behind
https://drone.caa.gov.tw/ airspace query):
  https://dronegis.caa.gov.tw/server/rest/services/Hosted/UAV_fs_ryg/FeatureServer/0

Two categories are bundled (small enough to ship; the 4000+ county polygons
are queried live by the page instead):
  機場四周禁止施放範圍                      -> kind=airport_no_fly   (red)
  機場四周距地面或水面200呎以上禁止施放範圍 -> kind=airport_alt_200ft (yellow)

Run:  python3 build-airports.py   (stdlib + curl only)
"""
import json
import os
import subprocess
import urllib.parse
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "airports.js")
BASE = ("https://dronegis.caa.gov.tw/server/rest/services/Hosted/"
        "UAV_fs_ryg/FeatureServer/0/query?")

CATEGORIES = [
    ("機場四周禁止施放範圍", "airport_no_fly"),
    ("機場四周距地面或水面200呎以上禁止施放範圍", "airport_alt_200ft"),
]


def fetch_category(cat):
    params = {
        "where": f"空域類別名稱='{cat}'",
        "outFields": "空域名稱,主管機關名稱",
        "outSR": "4326",
        "f": "geojson",
    }
    out = subprocess.run(
        ["curl", "-sSL", "--fail", "-A", "Mozilla/5.0", "--max-time", "120",
         BASE + urllib.parse.urlencode(params)],
        capture_output=True, text=True, check=True).stdout
    d = json.loads(out)
    if d.get("properties", {}).get("exceededTransferLimit"):
        raise SystemExit(f"{cat}: exceededTransferLimit — add resultOffset paging")
    return d["features"]


def round_coords(obj):
    if isinstance(obj, float):
        return round(obj, 6)
    if isinstance(obj, list):
        return [round_coords(x) for x in obj]
    return obj


def main():
    features = []
    for cat, kind in CATEGORIES:
        for f in fetch_category(cat):
            features.append({
                "type": "Feature",
                "properties": {"name": f["properties"].get("空域名稱"), "kind": kind},
                "geometry": {
                    "type": f["geometry"]["type"],
                    "coordinates": round_coords(f["geometry"]["coordinates"]),
                },
            })
        print(cat, "->", sum(1 for x in features if x["properties"]["kind"] == kind), "features")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by build-airports.py on %s — do not edit by hand.\n" % date.today())
        f.write("// Source: CAA dronegis UAV_fs_ryg feature service (official drone-map data).\n")
        f.write("window.AIRPORT_ZONES = ")
        json.dump({"type": "FeatureCollection", "features": features}, f,
                  ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"wrote {OUT}: {len(features)} polygons, {os.path.getsize(OUT)//1024} KB")


if __name__ == "__main__":
    main()
