#!/usr/bin/env python3
"""Convert the CAA restricted-airspace KML into zones.js for the fly-check page.

Source KML: data/caa-rcr-total.kml
  downloaded from https://www.caa.gov.tw/FileAtt.ashx?lang=1&id=5617
  ("(總)限航區範圍", linked from https://www.caa.gov.tw/Article.aspx?a=1293&lang=1)

The KML stores each RCR zone as one closed LineString inside a folder named
after the zone. Two extra "聚合線" groups are circles around 東沙 (Pratas) and
南沙/太平島, drawn as 32 separate 2-point arc segments that must be chained.

Output: zones.js defining window.CAA_ZONES (GeoJSON) and window.AIRPORTS.
Run:  python3 build-zones.py
"""
import json
import os
import xml.etree.ElementTree as ET
from datetime import date

NS = "{http://www.opengis.net/kml/2.2}"
HERE = os.path.dirname(os.path.abspath(__file__))
KML = os.path.join(HERE, "data", "caa-rcr-total.kml")
OUT = os.path.join(HERE, "zones.js")

# Major airports / airfields, for the approximate proximity warning layer.
# Coordinates are airfield reference points (approximate). radius_km is NOT
# the legal boundary — the law defines per-airport polygons; this is a
# deliberately conservative circle for a "check the official map" warning.
AIRPORTS = [
    ("台北松山 Songshan (TSA)", 25.0694, 121.5525),
    ("桃園國際 Taoyuan (TPE)", 25.0777, 121.2328),
    ("新竹基地 Hsinchu AB", 24.8167, 120.9390),
    ("台中清泉崗 Taichung (RMQ)", 24.2647, 120.6206),
    ("嘉義 Chiayi (CYI)", 23.4618, 120.3929),
    ("台南 Tainan (TNN)", 22.9504, 120.2058),
    ("高雄小港 Kaohsiung (KHH)", 22.5771, 120.3500),
    ("岡山基地 Gangshan AB", 22.7825, 120.2630),
    ("屏東 Pingtung", 22.6879, 120.4617),
    ("恆春 Hengchun (HCN)", 22.0411, 120.7302),
    ("台東豐年 Taitung (TTT)", 22.7550, 121.1017),
    ("台東志航基地 Chihhang AB", 22.7930, 121.1830),
    ("綠島 Green Island (GNI)", 22.6739, 121.4665),
    ("蘭嶼 Orchid Island (KYD)", 22.0270, 121.5350),
    ("花蓮 Hualien (HUN)", 24.0231, 121.6180),
    ("澎湖馬公 Magong (MZG)", 23.5687, 119.6280),
    ("七美 Qimei (CMJ)", 23.2130, 119.4180),
    ("望安 Wang-an (WOT)", 23.3674, 119.5028),
    ("金門 Kinmen (KNH)", 24.4279, 118.3592),
    ("馬祖南竿 Nangan (LZN)", 26.1598, 119.9581),
    ("馬祖北竿 Beigan (MFK)", 26.2240, 120.0026),
]


def coords_of(linestring):
    pts = []
    for tok in linestring.findtext(NS + "coordinates", "").split():
        lng, lat = map(float, tok.split(",")[:2])
        pts.append([round(lng, 6), round(lat, 6)])
    return pts


def chain_segments(segs, tol=1e-4):
    """Join 2-point arc segments into one ring (endpoints match within tol)."""
    segs = [list(s) for s in segs]
    ring = segs.pop(0)
    while segs:
        end = ring[-1]
        for i, s in enumerate(segs):
            if abs(s[0][0] - end[0]) < tol and abs(s[0][1] - end[1]) < tol:
                ring.extend(s[1:])
                segs.pop(i)
                break
            if abs(s[-1][0] - end[0]) < tol and abs(s[-1][1] - end[1]) < tol:
                ring.extend(reversed(s[:-1]))
                segs.pop(i)
                break
        else:
            raise ValueError(f"could not chain ring, {len(segs)} segments left")
    return ring


def close_ring(ring):
    if ring[0] != ring[-1]:
        ring.append(list(ring[0]))
    return ring


def main():
    root = ET.parse(KML).getroot()
    parent = {c: p for p in root.iter() for c in p}

    def folder_name(el):
        while el in parent:
            el = parent[el]
            if el.tag == NS + "Folder":
                return el.findtext(NS + "name", "")
        return ""

    named = {}       # zone name -> ring
    poly_groups = {} # 聚合線 group -> [segments]
    for ls in root.iter(NS + "LineString"):
        fname = folder_name(ls)
        pts = coords_of(ls)
        if fname.startswith("聚合線"):
            poly_groups.setdefault(fname, []).append(pts)
        elif fname.startswith("RCR"):
            named[fname] = close_ring(pts)

    features = [
        {
            "type": "Feature",
            "properties": {"name": name, "kind": "restricted"},
            "geometry": {"type": "Polygon", "coordinates": [ring]},
        }
        for name, ring in sorted(named.items())
    ]

    for gname, segs in poly_groups.items():
        ring = close_ring(chain_segments(segs))
        lat = ring[0][1]
        label = "南沙太平島周邊 (Spratly)" if lat < 15 else "東沙周邊 (Pratas)"
        features.append({
            "type": "Feature",
            "properties": {"name": label, "kind": "restricted"},
            "geometry": {"type": "Polygon", "coordinates": [ring]},
        })

    geojson = {"type": "FeatureCollection", "features": features}
    airports = [{"name": n, "lat": lat, "lng": lng} for n, lat, lng in AIRPORTS]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by build-zones.py on %s — do not edit by hand.\n" % date.today())
        f.write("// Source: CAA (總)限航區範圍 KML, caa.gov.tw Article a=1293 (last updated 2018/08/31).\n")
        f.write("window.CAA_ZONES = ")
        json.dump(geojson, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\nwindow.AIRPORTS = ")
        json.dump(airports, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"wrote {OUT}: {len(features)} zones, {len(airports)} airports")


if __name__ == "__main__":
    main()
